# SwiftLint Rules version 0.25.0

disabled_rules:
  - attributes
  - block_based_kvo
  - closure_end_indentation
  - compiler_protocol_init
  - class_delegate_protocol
  - closure_parameter_position
  - conditional_returns_on_newline
  - custom_rules
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_optional_boolean
  - dynamic_inline
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - fallthrough
  - force_cast
  - force_try
  - force_unwrapping
  - generic_type_name
  - identifier_name
  - implicitly_unwrapped_optional
  - large_tuple
  - let_var_whitespace
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - notification_center_detachment
  - object_literal
  - operator_whitespace
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_over_fileprivate
  - switch_case_on_newline
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - strict_fileprivate
  - sorted_imports
  - superfluous_disable_command
  - type_name
  - vertical_whitespace
  - xctfail_message

opt_in_rules:
  - array_init
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - contains_over_first_not_nil
  - control_statement
  - cyclomatic_complexity
  - discouraged_object_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_length
  - first_where
  - for_where
  - function_body_length
  - function_parameter_count
  - implicit_getter
  - implicit_return
  - is_disjoint
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - void_return
  - weak_delegate
  - yoda_condition

line_length: 120
file_length:
  warning: 500
  error: 1000
function_body_length: 50
type_body_length: 500
function_parameter_count: 8

file_header:
  required_pattern: |
                      \/\/
                      \/\/  Copyright © \d{4} Gnosis Ltd\. All rights reserved\.
                      \/\/
excluded:
  - safe/generated
  - SafeUIKit/generated
  
