# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.107.0"

default_platform :ios

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

def set_bundle_id(id)
  ENV["FASTLANE_APP_IDENTIFIER"] = id
end

platform :ios do

  before_all do
    ADHOC_APP_ID = ENV["FASTLANE_APP_IDENTIFIER"] + ".adhoc"
    DEV_APP_ID = ENV["FASTLANE_APP_IDENTIFIER"] + ".dev"
    PRERELEASE_APP_ID = ENV["FASTLANE_APP_IDENTIFIER"] + ".prerelease"
    BUILD_LOG_PATH = "Build/build_logs"
    DERIVED_DATA_PATH = "."
    BUILD_PATH = "Build"
    ARCHIVE_PATH = "Build/Archive"
    REPORTS_PATH = "Build/reports"
    workspace = "safe.xcworkspace"
    ENV["GYM_WORKSPACE"] = workspace
    ENV["SCAN_WORKSPACE"] = workspace
    PROJECT = "safe/safe.xcodeproj"
    if is_ci
      setup_travis
      increment_build_number(build_number: ENV["TRAVIS_BUILD_NUMBER"], xcodeproj: PROJECT)
    end
  end

  desc "Runs tests"
  lane :test do |options|
    do_run_tests(scheme: options[:scheme])
  end

  def do_run_tests(params)
    set_bundle_id DEV_APP_ID
    run_tests({configuration: "Debug", 
      skip_build: true, 
      slack_only_on_failure: true, 
      result_bundle: true,
      output_directory: REPORTS_PATH,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH,
      devices: ['iPhone X']}.merge(params))
  end

  desc "Runs all tests"
  lane :test_all do
    do_run_tests(scheme: "allUITests")
    do_run_tests(scheme: "safe")
  end

  desc "Build and distribute build to Fabric Beta"
  lane :fabric do
    #NOTE: disabled until CI migration
    #test_all
    set_bundle_id ADHOC_APP_ID
    match(type: "adhoc", app_identifier: ADHOC_APP_ID, clone_branch_directly: true)
    gym(configuration: "AdHoc", 
      scheme: "safe", 
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH,
      build_path: BUILD_PATH,
      archive_path: ARCHIVE_PATH)
    crashlytics(groups: "ios-beta-testers", notifications: false)
    slack(
     message: "Successfully distributed new version to Fabric beta :rocket:",
    )
  end

  lane :add_devices do
    register_devices(devices_file: "../gnosis-ios-certificates/devices.txt")
    match(type: "adhoc", app_identifier: ADHOC_APP_ID, force_for_new_devices: true)
  end

  desc "Submit a new PreRelease Rinkeby Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :prerelease do
    set_bundle_id PRERELEASE_APP_ID
    build_number = latest_testflight_build_number(app_identifier: PRERELEASE_APP_ID)
    increment_build_number(
      build_number: build_number + 1,
      xcodeproj: PROJECT
    )
    match(type: "appstore", app_identifier: ENV["FASTLANE_APP_IDENTIFIER"])
    gym(configuration: "PreRelease",
      scheme: "safe", 
      include_symbols: true,
      include_bitcode: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH,
      build_path: BUILD_PATH,
      archive_path: ARCHIVE_PATH
      )
    pilot(skip_waiting_for_build_processing: true,
      app_identifier: PRERELEASE_APP_ID)
    slack(
     message: "Successfully distributed new version to TestFlight :rocket:",
    )
  end

  lane :certificates do |options|
    is_readonly = !options[:force]
    match(type: "appstore", app_identifier: [ENV["FASTLANE_APP_IDENTIFIER"], PRERELEASE_APP_ID], readonly: is_readonly)
    set_bundle_id DEV_APP_ID
    match(type: "development", app_identifier: DEV_APP_ID, readonly: is_readonly)
    set_bundle_id ADHOC_APP_ID
    match(type: "adhoc", app_identifier: ADHOC_APP_ID, readonly: is_readonly)
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
