#! /usr/bin/env bash

set -ex
MERGE_SCRIPT=${SRCROOT}/../scripts/merge_strings.rb
TEMP_FILE=Localizable.strings

# Pass custom localization function name used in the source code
LOCALIZE_FUNC_NAME=""
if [ "$1" != "" ]; then
    LOCALIZE_FUNC_NAME="-s $1"
fi

# generate Localizable.strings for every Swift file in the project
find ${SRCROOT} -name "*.swift" -and -not -name "NSLocalizedString.swift" | xargs genstrings -o . $LOCALIZE_FUNC_NAME

# If no localized strings exist in the project, then Localizable.strings won't be generated by genstrings
if [ ! -e $TEMP_FILE ]; then
    exit 0
fi

# genstrings produces UTF-16LE encoded files on Mac OS, so we convert it to UTF-8 for easier processing
# NOTE: if localization language is not supported by UTF-8, we'll have to change the MERGE_SCRIPT for that.
iconv -f utf-16 -t utf-8 $TEMP_FILE > "${TEMP_FILE}.utf8"
mv "${TEMP_FILE}.utf8" $TEMP_FILE

# Merge genstrings' file with each localization's strings file
find ${SRCROOT} -name "Localizable.strings" -print0 | xargs -0 -I STRINGS_FILE $MERGE_SCRIPT $TEMP_FILE STRINGS_FILE

# Remove generated file
rm $TEMP_FILE
