#! /usr/bin/env bash

set -ex
MERGE=${SRCROOT}/../scripts/merge_strings.rb
GENERATED_STRINGS=Localizable.strings

# Pass custom localization function name used in the source code
LOCALIZE_FUNC_NAME=""
if [ "$1" != "" ]; then
    LOCALIZE_FUNC_NAME="-s $1"
fi

SOURCE_DIR="${SRCROOT}"
if [ "$2" != "" ]; then
    SOURCE_DIR="${SRCROOT}/$2"
fi

# generate Localizable.strings for every Swift file in the project
find ${SOURCE_DIR} -name "*.swift" \
    -and -not -name "NSLocalizedString.swift" \
    -and -not -name "LocalizedString.swift" | xargs genstrings -o . $LOCALIZE_FUNC_NAME

# If no localized strings exist in the project, then Localizable.strings won't be generated by genstrings
if [ ! -e $GENERATED_STRINGS ]; then
    exit 0
fi

# genstrings produces UTF-16LE encoded files on Mac OS, so we convert it to UTF-8 for easier processing
# NOTE: if localization language is not supported by UTF-8, we'll have to change the MERGE for that.
iconv -f utf-16 -t utf-8 $GENERATED_STRINGS > "${GENERATED_STRINGS}.utf8"
mv "${GENERATED_STRINGS}.utf8" $GENERATED_STRINGS

# Merge genstrings' file with each localization's strings file
find ${SOURCE_DIR} -name "Localizable.strings" \
    -and -not -path "*.bundle/*" \
    -and -not -path "*.framework/*" -print0 | xargs -0 -I EXISTING_STRINGS $MERGE $GENERATED_STRINGS EXISTING_STRINGS

# Remove generated file
rm $GENERATED_STRINGS
