//
//  Copyright © 2018 Gnosis Ltd. All rights reserved.
//

import Foundation

struct InfuraServiceConfiguration {

    static let rinkeby =
        // Keys are autogenerated during build
        InfuraServiceConfiguration(chainID: 4,
                                   endpoint: URL(string: "https://rinkeby.infura.io/\(Keys.infuraApiKey)")!)

    var chainID: Int
    var endpoint: URL

    init(chainID: Int, endpoint: URL) {
        self.chainID = chainID
        self.endpoint = endpoint
    }

}
